apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
    role: server
    tier: backend
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: elasticsearch
      role: server
      tier: backend
  template:
    metadata:
      labels:
        app: elasticsearch
        role: server
        tier: backend
    spec:
      containers:
      - name: elasticsearch
        securityContext:
          privileged: true
          capabilities:
            add:
              - IPC_LOCK
        image: ackee/docker-elasticsearch:latest
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CLUSTER_NAME
          value: %PROJECT_NAME%
        - name: ES_MASTER
          value: "true"
        - name: ES_DATA
          value: "true"
        - name: ES_INGEST
          value: "true"
        - name: HTTP_ENABLED
          value: "true"
        - name: ES_JAVA_OPTS
          value: -Xms1024m -Xmx1024m
        - name: NETWORK_HOST
          value: _site_,_lo_
        - name: "GCE_PROJECT"
          value: "%PROJECT_NAME%"
        - name: "GCE_ZONE"
          value: europe-west1-d
        - name: PROCESSORS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        resources:
          requests:
            cpu: 250m
            memory: 1024Mi
          limits:
            cpu: 1
            memory: 2048Mi
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: transport
          initialDelaySeconds: 220
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_cluster/health
            port: http
          initialDelaySeconds: 220
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: elasticsearch-data
      initContainers:
      - name: sysctl
        securityContext:
          privileged: true
        image: busybox
        command:
         - sysctl
         - "-w"
         - "vm.max_map_count=262144"
      - name: fixperms
        securityContext:
          privileged: true
        image: busybox
        command:
         - chown
         - "-R"
         - "1000:1000"
         - "/usr/share/elasticsearch/data"
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: elasticsearch-data
      volumes:
        - name: elasticsearch-data
          persistentVolumeClaim:
            claimName: elasticsearch-%PROJECT_NAME%-%APP_NAME%-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
    role: server
    tier: backend
spec:
  selector:
    app: elasticsearch
    role: server
    tier: backend
  ports:
  - name: http
    port: 9200
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-discovery
  labels:
    app: elasticsearch
    role: server
    tier: backend
spec:
  selector:
    app: elasticsearch
    role: server
    tier: backend
  ports:
  - name: transport
    port: 9300
    protocol: TCP
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-%PROJECT_NAME%-%APP_NAME%-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
