cluster:
  name: ${CLUSTER_NAME:ackee}

node:
  master: ${ES_MASTER:true}
  data: ${ES_DATA:false}
  name: ${HOSTNAME}
  ingest: ${ES_INGEST:false}

processors: ${PROCESSORS:1}

network.host: _site_,_lo_

bootstrap:
  memory_lock: ${MEMORY_LOCK:false}

http:
  enabled: ${HTTP_ENABLED:true}
  compression: true
  cors:
    enabled: ${HTTP_CORS_ENABLE:true}
    allow-origin: ${HTTP_CORS_ALLOW_ORIGIN:*}

cloud.gce.project_id: ${GCE_PROJECT:dummy}
cloud.gce.zone: ${GCE_ZONE:dummy}

discovery:
  zen:
    hosts_provider: gce
    ping:
      unicast:
        hosts: ${DISCOVERY_SERVICE:elasticsearch-discovery}
